"""Agent that manages multiple tool using agents"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../../nbs/agents/00_management_agent.ipynb.

# %% auto 0
__all__ = []

# %% ../../nbs/agents/00_management_agent.ipynb 4
import datetime
from dataclasses import dataclass
from typing import Literal
from httpx import AsyncClient, ConnectError, ConnectTimeout, RemoteProtocolError
import requests

from pydantic import BaseModel, Field
from rich.prompt import Prompt

from pydantic_ai import Agent, ModelRetry, RunContext
from pydantic_ai.messages import ModelMessage
from pydantic_ai.usage import Usage, UsageLimits
from pydantic_ai.tools import Tool

from .orchestration_agent import build_orchestration_agent, _OrchestrationPlan

# %% ../../nbs/agents/00_management_agent.ipynb 5
class _ManagementResponse(BaseModel):
    """Response from the manager"""
    final_result: str = Field(..., description="The final result of the request structured using markdown and latex")
    final_goal_completed: bool = Field(..., description="Whether the final goal was completed")
    final_goal: str = Field(..., description="The final goal of the request")
    evedence: list[str] = Field(..., description="The evidence for the final result")
    plan: list[str] = Field(..., description="The plan to achieve the final goal")
    plan_completed: bool = Field(..., description="Whether the plan was completed")
