"""This agent is designed to call plan agent actions from a given prompt and use expert agents efficiently"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../../nbs/agents/01_orchestration_agent.ipynb.

# %% auto 0
__all__ = ['build_orchestration_agent']

# %% ../../nbs/agents/01_orchestration_agent.ipynb 2
import datetime
from dataclasses import dataclass
from typing import Literal
from httpx import AsyncClient, ConnectError, ConnectTimeout, RemoteProtocolError
import requests

from pydantic import BaseModel, Field
from rich.prompt import Prompt

from pydantic_ai import Agent, ModelRetry, RunContext
from pydantic_ai.messages import ModelMessage
from pydantic_ai.usage import Usage, UsageLimits

# %% ../../nbs/agents/01_orchestration_agent.ipynb 3
class _OrchestrationPlan(BaseModel):
    """Plan for orchestration of agent models and tools to solve a users main goal"""
    main_goal: str
    sub_goals: list[str] = Field(description=(
        "List of sub goals needed to achieve the main goal, "
        "sub goals should be simple and achievable with the tools and models available. "
        "Sub goals can reference other sub goals or the main goal. "
        "Sub goals must include a reason for why they are needed to achieve the main goal.")
        )
    plan: list[str] =  Field(description="List of steps to achieve the main goal along with sub goals")

# %% ../../nbs/agents/01_orchestration_agent.ipynb 7
def build_orchestration_agent():
    return Agent[None, _OrchestrationPlan](
    "openai:gpt-4o-mini", 
    result_type=_OrchestrationPlan,
    system_prompt=(
        "You are an expert at orchestrating models and tools to solve complex problems. "
        "You break down problems into simple sub-goals and plan out the steps needed to achieve them. "
        "You have been asked to help a user achieve their main goal. "
        "The user has provided a prompt you must determine the main goal to best help them. "
        "You must then determine the sub-goals needed to achieve the main goal and plan out the steps needed to achieve them. "
        "You are able to use a number of tools and models to help you achieve the main goal. "
    )
    )
