"""This agent is designed to call plan agent actions from a given prompt and use expert agents efficiently"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../../nbs/agents/00_orchestration_agent.ipynb.

# %% auto 0
__all__ = ['OchestrationPlan']

# %% ../../nbs/agents/00_orchestration_agent.ipynb 2
import datetime
from dataclasses import dataclass
from typing import Literal

from pydantic import BaseModel, Field

from pydantic_ai import Agent, ModelRetry, RunContext
from pydantic_ai.messages import ModelMessage
from pydantic_ai.usage import Usage, UsageLimits

# %% ../../nbs/agents/00_orchestration_agent.ipynb 3
class OchestrationPlan(BaseModel):
    """Plan for orchestration of agent models and tools to solve a users main goal"""
    main_goal: str
    sub_goals: list[str] = Field(description=(
        "List of sub goals needed to achieve the main goal, "
        "sub goals should be simple and achievable with the tools and models available. "
        "Sub goals can reference other sub goals or the main goal. "
        "Sub goals must include a reason for why they are needed to achieve the main goal.")
        )
    plan: list[str] =  Field(description="List of steps to achieve the main goal along with sub goals")
