# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/agent_chatbot',
                'doc_host': 'https://redam94.github.io',
                'git_url': 'https://github.com/redam94/agent_chatbot',
                'lib_path': 'agent_chatbot'},
  'syms': { 'agent_chatbot.agents.manager_agent': { 'agent_chatbot.agents.manager_agent._ManagementResponse': ( 'agents/management_agent.html#_managementresponse',
                                                                                                                'agent_chatbot/agents/manager_agent.py')},
            'agent_chatbot.agents.orchestration_agent': { 'agent_chatbot.agents.orchestration_agent._OrchestrationPlan': ( 'agents/orchestration_agent.html#_orchestrationplan',
                                                                                                                           'agent_chatbot/agents/orchestration_agent.py'),
                                                          'agent_chatbot.agents.orchestration_agent.build_orchestration_agent': ( 'agents/orchestration_agent.html#build_orchestration_agent',
                                                                                                                                  'agent_chatbot/agents/orchestration_agent.py')},
            'agent_chatbot.app': {}}}
